secretKey: your_secretKey
IV: your_custom_IV

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_root_name
    password: your_root_password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
